# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: npm i

      - name: test
        run: npm test
